### ISSUE TITLE
Allow me to pass custom preprocessor flags to the "keymap" CLI

### ISSUE THREAD

**Issue by Townk** [caksoylar/keymap-drawer#103]
In my [ZMK user configuration](https://github.com/Townk/zmk-config), I use a [ZMK feature](https://github.com/Townk/zmk-config/blob/master/config/layout/standard_layout.dtsi#L28) that was not merged yet ([PR #1984](https://github.com/zmkfirmware/zmk/pull/1984)).

To allow the GitHub action to build my layout without errors, I surrounded it with an `#ifndef`:

```cpp
#ifndef USE_MOLOCK
#define LOCK_LAYER &none
#else
#define LOCK_LAYER &molock
#endif
```

This allows me to use the ZMK `DTS_EXTRA_CPPFLAGS` flag to make the `USE_MOLOCK` macro defined during local build:

```sh
west build -p -d build/corne-left -b nice_nano_v2 -- \
    -DSHIELD=corne_left \
    -DDTS_EXTRA_CPPFLAGS="-DUSE_MOLOCK=1" \
    -DZMK_CONFIG="$TOWNK_ZMK_CONFIG_DIR/config"
```

I would like to have a similar feature on Keymap-Drawer, so I can make the image generation to consider that branch of the check. For instance, I would like to use something like this:

```sh
keymap -c "keymap-config.yaml" \
    --preprocessor-extra-flags "-DUSE_MOLOCK" \
    draw -o "keymap-layout.svg" \
    "keymap-layout.yaml"
```

Or perhaps a configuration attribute in the `parse_config` section of the KD config file:

```yaml
parse_config:
    preprocessor_flags: -DDTS_EXTRA_CPPFLAGS="-DUSE_MOLOCK=1"
```

I could try to use the built-in `KEYMAP_DRAWER` macro, but if I have more than one of these feature-flags on my layout, it would be an "all-or-nothing" from the Keymap-Drawer perspective.

**Comment by caksoylar** [comment]
I am planning to add this as a new config item `parse_config.zmk_preprocessor_preamble`, with the default value of `#define KEYMAP_DRAWER`. This would let you cover above scenario via:

```yaml
parse_config:
  zmk_preprocessor_preamble: |
    #define KEYMAP_DRAWER
    #define USE_MOLOCK
```

Does that work for your use case, as opposed to a CLI argument[^1]?

[^1]: While it isn't 100% consistent, there are two factors I consider when deciding where a new setting goes:
    1. Does it make sense to share across keyboards, e.g. it makes sense that legend overrides are not keyboard-specific, whereas layer names that you want to draw might be (one inconsistency here might be `zmk_combos`, since your combos aren't necessarily shared across keyboards)
    2. How hard is it to actually use in the command line (`zmk_combos` would be pretty hard in the shell, hence it is in config)

    In this case, IMO reason i. slightly leans towards CLI argument but reason ii. seems stronger in favor of a config option.

**Comment by Townk** [comment]
Yep, that would be perfect!

**Comment by caksoylar** [comment]
I implemented this as above (just renamed to `zmk_preamble` without `_preprocessor`), please give it a try.

**Comment by Townk** [comment]
It works perfectly! Now we have config flags parity with ZMK :).
