### ISSUE TITLE
web app: Error while drawing SVG from keymap YAML

### ISSUE THREAD

**Issue by szczys** [caksoylar/keymap-drawer#110]
I suspect the release of 0.18.0 earlier today caused an issue with the web app where it is unable to render the SVG files (even for the example yaml):

![image](https://github.com/user-attachments/assets/e8628ad9-72d5-4eda-b992-4f5559ff1d86)

This is a fantastic visualization tool. Thanks for all the work you've put into it!

**Comment by caksoylar** [comment]
Thanks for reporting, I hadn't noticed it! Looking into it now.

**Comment by caksoylar** [comment]
I don't know why it happened but doing a reboot seems to have fixed it? Please let me know if you have issues!

**Comment by szczys** [comment]
Looks like it's working now. Thanks!
