### ISSUE TITLE
Workflows fail due to externally managed environment

### ISSUE THREAD

**Issue by quintuple-lained** [caksoylar/keymap-drawer#119]
I noticed that my draw workflow in my own zmk repository [failed ](https://github.com/quintuple-lained/lained-ergonaut-keymap/actions/runs/11340664011), after trying it with a fork of one of the "hall of fame" repositories the same issue [occurred](https://github.com/quintuple-lained/zmk-config/actions/runs/11340916953/job/31538193466#step:4:25). My guess would be that this is due to a change in distro choice for githubs workers

**Comment by caksoylar** [comment]
Can you try again? I just merged #118.

**Comment by quintuple-lained** [comment]
yep, it runs now, unfortunate timing on my issue and my fault for not checking prs as well, thank you

**Comment by caksoylar** [comment]
Not at all, thanks for reporting!
