### ISSUE TITLE
ZMK parsing combos are not output in newer version

### ISSUE THREAD

**Issue by magicDGS** [caksoylar/keymap-drawer#137]
On the new version released, the parsing of the zmk-config file doesn't output the combos anymore. Probably there is something missing in the new tree-sitter parser code.

**Comment by caksoylar** [comment]
Can you share an example? It works on all my test cases, so it isn't broken in general.

**Comment by magicDGS** [comment]
Sorry, it was a bit late when I wrote that and I did not relized that I was using a conda environment with an experimental version that I was checking. Closing as it was my own fault.
