### ISSUE TITLE
Better parsing and output of mod + key press

### ISSUE THREAD

**Issue by lilactown** [caksoylar/keymap-drawer#16]
Currently, ZMK key presses like `&kp LG(GRAVE)` and `&kp LS(LC(TAB))` are output verbatim. It would be nice if they were parsed and output in a prettier way. I am currently modifying my keymap YAML file so they look something like:

```
  - {t: GRAVE, h: LGUI}
  - {t: TAB, h: LSFT, LCTL}
```

I think `t` is supposed to be tap and `h` hold. maybe there's another thing, `m` that could place the modifier at the top of the key instead of the bottom?

**Comment by lilactown** [comment]
Ah this looks like it would be fixed by closing https://github.com/caksoylar/keymap-drawer/issues/9#issue-1607529929 too

**Comment by caksoylar** [comment]
Hey, that is true, cleaner legends for keys with modifiers is one of the motivations for #9. However I don't know a cleaner way to display them without using icons -- let me know if you have any ideas. Maybe we could at least chop off the `L/R` prefix from modifier functions.

By the way sublegends at the top of the key is currently supported with `shifted/s` field, see the key spec [here](https://github.com/caksoylar/keymap-drawer/blob/main/KEYMAP_SPEC.md#layers). They are supposed to represent shifted version of keys, e.g. `{t: 1, s: !}` or alternative functions via mod-morph, but they aren't parsed from the keymaps yet. You are free to reuse them to display other things, of course 😄

**Comment by lilactown** [comment]
I think the icons is a good idea. Do you think that we could build it into the config the ability to customize what modifiers are output as?

```yaml
parse_config:
  mod_map:
    GUI: ⌘
    CTRL: ⌃
    ALT: ⎇
    SHIFT: ⇧
```

Then the parser could then map the various representations of mods, e.g. `&kp LG(GRAVE)` to

```
⌘`
```

And `&kp LS(LC(TAB))` to `⇧⌃ TAB`

**Comment by caksoylar** [comment]
Yeah, that sounds good. I'll close this and copy your comment to #9.
