### ISSUE TITLE
Fetched SVGs not showing in web app or embedded in readme.md

### ISSUE THREAD

**Issue by bennytrouser** [caksoylar/keymap-drawer#25]
When using the new feature to fetch SVG from supported sources (e.g. ```$$material:keyboard_return$$```), they show in chrome when viewing the layout directly, but show up blank in the web app or when I embed the layout svg in my github readme. They also show up fine in inkscape.

**Comment by bennytrouser** [comment]
Seems to be ok now for some reason

**Comment by caksoylar** [comment]
I think I also saw this behavior in some cases (e.g. for glyphs in the header image in the README) in some contexts but I haven't seen it frequently enough to nail it down. If I see it again I'll see if there is anything to be improved, I think it will be hard to debug this remotely.
