### ISSUE TITLE
Some config options don't seem to have any effect, unclear why

### ISSUE THREAD

**Issue by minusfive** [caksoylar/keymap-drawer#38]
E.g., for Corne-ish Zen (and I imagine all cornes?) neither `key_w` nor `split_gap` seem to have any effect.

**Comment by caksoylar** [comment]
Those settings are only used by the ortho layout generator, see comments at https://github.com/caksoylar/keymap-drawer/blob/main/keymap_drawer/config.py#L13 (I know, they need to be documented properly 😞)

**Comment by minusfive** [comment]
Gotcha! No worries, docs are never done man. So I should be able to further customize by essentially cloning the `corne_rotated` layout, tweak it and pass it as a param to the command, right?

**Comment by caksoylar** [comment]
Yes, you can customize it as you like and then pass it with `-j ...json` argument. Or. if you have it next to the keymap file with name `corneish_zen.json` then it will be used automatically. This was originally added to support keymap-editor which creates/uses that json.

**Comment by minusfive** [comment]
> Or. if you have it next to the keymap file with name `corneish_zen.json` (i.e. `.keymap` replaced by `.json`) then the workflow will pick it up automatically.

![image](https://github.com/caksoylar/keymap-drawer/assets/33695/db0adf03-9928-446b-920c-b82925663a9a)
