### ISSUE TITLE
Feature request: render specific layer(s)

### ISSUE THREAD

**Issue by MattSturgeon** [caksoylar/keymap-drawer#51]
## Premise

After parsing my keymap, it'd be great to have a cli arg and/or config option to specify which layer(s) to be included in the SVG.

I believe the only way to achieve this currently is to edit the generated yaml file and remove the layers that I don't want to render.

## Example API

```sh
# CLI

# Stringified list approach, would need to parse into an actual list,
# trim whitespace, etc:
--include-layers "1, 2, Navigation"

# Alternative approach, no parsing needed...
--incude-layer 1 --include-layer 2 --include-layer Navigation

# Either way, single layer should work as expected:
--include-layer Navigation
```

```yaml
# YAML
draw_config:
  included_layers:
  - 1
  - 2
  - Navigation
```

```yaml
# YAML (can be a list or a string)
draw_config:
  included_layers: Navigation
```

It'd be good (but not necessary) for layer id, label, name, etc to all be understood.

## Use case

I'd like to render specific layers into their own svg file, e.g. `nav_layer.svg` & `symbols_layer.svg`. It may also be useful to render a slice of layers into an svg; `special_layers.svg`.

This would make it easier to have an image of a specific layer included with that layer's documentation.

Also, it would simplify printing off a paper copy of _the one layer I changed a bunch and need to re-learn_.

I would probably split up my CI workflow

- A `commit` job that depends on several `render` jobs - commits the rendered SVGs
- Several `render` jobs that each depend on a `parse` job (run in parallel)
- A `parse` job - generates the `config.yml`

**Comment by caksoylar** [comment]
Hello there, unless I am misunderstanding the request, this is already supported as an arg to `keymap draw`, (see https://github.com/caksoylar/keymap-drawer/blob/main/keymap_drawer/__main__.py#L129) e.g.

```sh
keymap draw -s 1 2 Navigation -- keymap.yaml
```

A couple notes:
- Currently the syntax is `-s/--select-layers LAYER [LAYER ...]`, which necessitates `--` to separate the positional arguments. While `argparse` (built-in Python module) supports this for list-valued options, arguably better designed alternatives such as `click` and `typer` require repeating the switch, i.e. `-s L1 -s L2`. I experimented with the latter already at https://github.com/caksoylar/keymap-drawer/tree/typer (a bit outdated branch) so this might change at some point in the future.
- This a CLI-only switch, not supported by the configuration file. Conceptually I think of configuration file to be something that is keymap-independent, i.e. it should ideally apply to all the keymaps you own. This switch is too specific to the keymap to put in there. But let me know if you feel strongly about this.
  (I am aware that some config items already break this concept, such as `zmk_combos`, but that seemed necessary.)

**Comment by MattSturgeon** [comment]
Yes that's exactly what I was after. Not sure how I missed it... Thanks

**Comment by MattSturgeon** [comment]
In case anyone finds this thread and wants to do something similar, I ended up writing a [fairly crude CI Workflow](https://github.com/MattSturgeon/Glove80-Config/blob/ea0d3e30986a8836aaf83c567e14529d079b6301/.github/workflows/draw-keymaps.yml) that generates a separate SVG for each layer of every keymap found in `config/`.

(The layer names are extracted using a tiny little [PyYaml script](https://github.com/MattSturgeon/Glove80-Config/blob/ea0d3e30986a8836aaf83c567e14529d079b6301/.github/workflows/layers.py)).
