### ISSUE TITLE
Allow dict config for zmk_keycode_map and qmk_keycode_map

### ISSUE THREAD

**Issue by infused-kim** [caksoylar/keymap-drawer#6]
Hi,

First of all, thank you so much for creating this. It works really well and is super useful.

I have one small feature request: 

The `raw_binding_map` allows you to specify a dict that draws multiple symbols for a key, such as 
```yaml
  raw_binding_map:
     &mm_grescm_gui': {t: ESC, h: ⌘, s: '` ~'}
```

Since default `&kp` keys can also have multiple binding, such as `/ ?`, it would be great if we could assign multiple values to those too, like:
```yaml
  zmk_keycode_map:
    SLASH: {t: "/", s: '?'}
```

But currently this raises an error:
```shell
❯ keymap -c chocofi_keymap_config.yaml parse -c 10 -z ../config/corne.keymap > chocofi_keymap.yaml && keymap -c chocofi_keymap_config.yaml draw -k crkbd/rev1 chocofi_keymap.yaml > chocofi_keymap.svg
Traceback (most recent call last):
  File "/Users/Kim/.local/bin/keymap", line 8, in <module>
    sys.exit(main())
  File "/Users/Kim/.local/pipx/venvs/keymap-drawer/lib/python3.10/site-packages/keymap_drawer/__main__.py", line 147, in main
    config = Config.parse_obj(yaml.safe_load(f))
  File "pydantic/main.py", line 527, in pydantic.main.BaseModel.parse_obj
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for Config
parse_config -> qmk_keycode_map -> COMMA
  str type expected (type=type_error.str)
parse_config -> qmk_keycode_map -> DOT
  str type expected (type=type_error.str)
parse_config -> qmk_keycode_map -> SLASH
  str type expected (type=type_error.str)
parse_config -> qmk_keycode_map -> SLSH
  str type expected (type=type_error.str)
parse_config -> zmk_keycode_map -> SINGLE_QUOTE
  str type expected (type=type_error.str)
```

Thank you for taking the time to consider this.

**Comment by caksoylar** [comment]
Good idea, thanks! Please give the new version a shot and see if that works for you.

In the future I'll add shifted fields to the default `qmk/zmk_keycode_map` values and probably add a config to disable emitting them during parsing in case a user prefers not to.

**Comment by infused-kim** [comment]
Wow that was fast. Thank you.

I installed the new version, but unfortunately, it's not working:

```shell
❯ keymap -c chocofi_keymap_config.yaml parse -c 10 -z ../config/corne.keymap > chocofi_keymap.yaml && keymap -c chocofi_keymap_config.yaml draw -k crkbd/rev1 chocofi_keymap.yaml > chocofi_keymap.svg
Traceback (most recent call last):
  File "/Users/Kim/.local/bin/keymap", line 8, in <module>
    sys.exit(main())
  File "/Users/Kim/.local/pipx/venvs/keymap-drawer/lib/python3.10/site-packages/keymap_drawer/__main__.py", line 155, in main
    parse(args, config.parse_config)
  File "/Users/Kim/.local/pipx/venvs/keymap-drawer/lib/python3.10/site-packages/keymap_drawer/__main__.py", line 64, in parse
    parsed = ZmkKeymapParser(config, args.columns).parse(args.zmk_keymap)
  File "/Users/Kim/.local/pipx/venvs/keymap-drawer/lib/python3.10/site-packages/keymap_drawer/parse.py", line 43, in parse
    return self._parse(f)
  File "/Users/Kim/.local/pipx/venvs/keymap-drawer/lib/python3.10/site-packages/keymap_drawer/parse.py", line 254, in _parse
    layers = self._get_layers(parsed)
  File "/Users/Kim/.local/pipx/venvs/keymap-drawer/lib/python3.10/site-packages/keymap_drawer/parse.py", line 210, in _get_layers
    layers[layer_name] = [
  File "/Users/Kim/.local/pipx/venvs/keymap-drawer/lib/python3.10/site-packages/keymap_drawer/parse.py", line 211, in <listcomp>
    self._str_to_key("&" + stripped)
  File "/Users/Kim/.local/pipx/venvs/keymap-drawer/lib/python3.10/site-packages/keymap_drawer/parse.py", line 137, in _str_to_key
    return LayoutKey(tap=mapped(par))
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LayoutKey
t
  str type expected (type=type_error.str)

```

**Comment by caksoylar** [comment]
I think `keymap` might still be pointing to the version that you installed through `pipx` since the stack trace lines don't match the current `main`. I think you might be able to force it via `python -m keymap_drawer` in the `keymap-drawer` folder but it would be good to figure out the path issues.

**Comment by infused-kim** [comment]
You were right, I did a forced install from github over my existing install and I guess it didn't take. I uninstalled and installed it again and now it's working.

Thank you!

But I found a new small problem... Now the macro labels also contain the shifted versions, which is probably not the intended behavior.

Here's a screenshot:
<img width="866" alt="Screenshot 2023-03-02 at 15 39 46" src="https://user-images.githubusercontent.com/7404004/222562073-8e2f1054-0898-477c-9f72-ec15a6e9599e.png">

**Comment by infused-kim** [comment]
For me this not a big deal, so don't bother if this is something you also don't mind.

I don't think a config option is the way to go though. When someone defines a combo, I doubt their intention is to also use the shifted version of the combo, since that would require using a lot of contortion. They probably only have the combo for the unshifted version. 

At least that's my thinking and perhaps other people don't think that way. So, I would just disable rendering the shifted text on the combos.

**Comment by caksoylar** [comment]
I think there is value in hold fields in combos, since e.g. Miryoku uses them for layer activations with two thumb keys. Since I thought that made sense I had also added `shifted` support, although I admit there is less justification for that. I do use my combos with shift but I probably don't need it drawn since it makes the combo box unnecessarily busy.

I'll disable adding the shifted field during parsing, so they will still be drawn if they are in the YAML but parsing won't add them if they are in `zmk_binding_map` etc.
