### ISSUE TITLE
Upgrading to `v0.13.0` lose `trans_legend` config

### ISSUE THREAD

**Issue by haunt98** [caksoylar/keymap-drawer#62]
`v0.13.0`:

<img width="1035" alt="image" src="https://github.com/caksoylar/keymap-drawer/assets/5424272/2bdd52d0-870b-45b7-b8eb-b9136f80d1e3">

`v0.12.1`:

<img width="1017" alt="image" src="https://github.com/caksoylar/keymap-drawer/assets/5424272/0d5c9f57-b20c-4977-868c-f60d1f710dbc">

My config is [here](https://github.com/haunt98/qmk_keymaps/blob/main/caksoylar_keymap_drawer/config.yaml).

My guess is after adding `qmk_remove_keycode_prefix`: `KC_TRNS` become `TRNS`.

**Comment by caksoylar** [comment]
Thank you for the report, that is very probable! I'll try to fix it and publish a v0.13.1 tonight.

**Comment by haunt98** [comment]
Thank you, just take your time. I'm just testing daily 👍

**Comment by caksoylar** [comment]
Thanks again for the report, I believe I fixed it with v0.13.1. Can you test again?

**Comment by haunt98** [comment]
Thanks @caksoylar, it works again!

<img width="1002" alt="image" src="https://github.com/caksoylar/keymap-drawer/assets/5424272/fc57c093-83d8-4e1a-8b78-77a6ab2fa243">
