### ISSUE TITLE
tabler `viewbox` regex issue

### ISSUE THREAD

**Issue by SethMilliken** [caksoylar/keymap-drawer#81]
More tabler fun. Looks like they have recently changed the `<svg>` tag so that it is no longer all on one line, so the [`viewBox` regex](https://github.com/caksoylar/keymap-drawer/blob/f63ccf49bae1df2f58d3f6bab8a0fc13faf6c981/keymap_drawer/draw/glyph.py#L29) no longer matches.

- [sample of earlier version](view-source:https://unpkg.com/@tabler/icons@2.1.0/icons/brightness-up.svg)
- [sample of current version](view-source:https://unpkg.com/@tabler/icons@3.1.0/icons/outline/brightness-up.svg)
- [sample of resulting GitHub Action error](https://github.com/SethMilliken/zmk-config/actions/runs/8408768875/job/23025319008#step:5:68)

**Comment by SethMilliken** [comment]
FWIW, adding the [`re.DOTALL` flag](https://docs.python.org/3/library/re.html#re.DOTALL) might be sufficient here.

**Comment by caksoylar** [comment]
Closed by #82.
