### ISSUE TITLE
Feature Request: Using local layout file

### ISSUE THREAD

**Issue by lukevanlukevan** [caksoylar/keymap-drawer#96]
Hi there.

I have set this up locally, but can't seem to find any info about using a local layout file from my own QMK fork. Is this possible at the moment? If not, is it possible to add it?

**Comment by caksoylar** [comment]
Hi, if you are using the CLI, then you can pass it to the `keymap draw` command with `-j`/`--qmk-info-json`:

```sh
keymap draw -j path/to/info.json my_keymap.yaml
```

Does that answer the question?

**Comment by lukevanlukevan** [comment]
Thank you, that works too. I forked it and added a json file to the layouts. I appreciate the response

**Comment by caksoylar** [comment]
No problem, with the command line arg you can pass an arbitrary path and don't need a fork.
